### ISSUE TITLE
Not loading 0.96.0

### ISSUE THREAD

**Issue by jasperbom** [aendle/custom_components#10]
Works on 0.93.2 but when installing on a 0.96.0 it says: Platform not found: climate.smart_thermostat

**Comment by crackston** [comment]
Also not working here.  I changed my config from `climate: -platform: smart_thermostat `to just `smart_thermostat:` and it at least accepts the configuration.  However, I still get the notification `The following components and platforms could not be set up; check your config.`

The log file says "no setup function defined." Looking into what the new requirements are...

**Comment by crackston** [comment]
It looks like 0.96 has a lot of breaking changes to the climate component. I'm a novice in python and programming so I don't think I'll be able to handle this one:

> set_away_mode and set_hold_mode have been merged into set_preset_mode. So instead of turn_away_mode_on(), we will now call set_preset_mode("away").

https://developers.home-assistant.io/blog/2019/07/03/climate-cleanup.html
[Climate Cleanup](https://developers.home-assistant.io/blog/2019/07/03/climate-cleanup.html)
