### ISSUE TITLE
Successful?

### ISSUE THREAD

**Issue by medicshort87** [aendle/custom_components#2]
Do you have this successfully implemented into Home Assistant? I am trying to PID an electric smoker that is controlled by an ESP8266 via HA and I think this may be what I may need.

**Comment by aendle** [comment]
Hi
I would not do it with Home Assistant. It's ment for slow applications, not for something as fast as an electric smoker. You can look for an esp pid example and controll it directly on the controller. Or buy an Arduino. There are tons of examples and how to use them.
