### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by jasperbom** [aendle/custom_components#3]
I'm having some issues installing the PID controller in Home Assistant, can you tell me the procedure?

**Comment by aendle** [comment]
https://developers.home-assistant.io/docs/en/creating_component_index.html

**Comment by jasperbom** [comment]
Thank you for your reply. Unfortunately I can't get it to work...

> Error while setting up platform smart_thermostat
> Traceback (most recent call last):
>   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
>     SLOW_SETUP_MAX_WAIT, loop=hass.loop)
>   File "/usr/lib/python3.5/asyncio/tasks.py", line 400, in wait_for
>     return fut.result()
>   File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
>     raise self._exception
>   File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
>     result = coro.send(None)
>   File "/usr/lib/python3.5/asyncio/coroutines.py", line 210, in coro
>     res = func(*args, **kw)
>   File "/home/homeassistant/.homeassistant/custom_components/climate/smart_thermostat.py", line 124, in async_setup_platform
>     kd, pwm, autotune, noiseband)])
>   File "/home/homeassistant/.homeassistant/custom_components/climate/smart_thermostat.py", line 182, in __init__
>     self.pidAutotune = pid_controller.PIDAutotune(self._target_temp, self.difference,
> AttributeError: module 'pid_controller' has no attribute 'PIDAutotune'

**Comment by barankaynak** [comment]
I have the same problem
AttributeError: module 'pid_controller' has no attribute 'PIDAutotune'

**Comment by jasperbom** [comment]
Could you please help us?

**Comment by aendle** [comment]
did you install the pid module with pip?

**Comment by aendle** [comment]
I added an installation guide, if you follow it, I'm sure it works.
I testet it on a completly new ubuntu LTS server from scratch today
