### ISSUE TITLE
Error loading custom component on 0.89.0

### ISSUE THREAD

**Issue by piitaya** [aendle/custom_components#6]
Custom component structure change with 0.89.0 version. Here's the migration guide : https://www.home-assistant.io/blog/2019/03/06/release-89/#noteworthy-breaking-changes

I tried to rename the files but it does'nt work 😟

**Comment by flopon** [comment]
I've made a PR, merged by the owner of the project. You can try the current code, it works with the current version of Home Assistant (0.93.2).
